FileStorage/Controllers/FileUploadController.cs
using BLL.DTO;
using BLL.Services;
using BLL.Services.Interfaces;
using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FileStorage.Controllers
{
    [Authorize(Roles = "user")]
    public class FileUploadController : Controller
    {
        private readonly IFileDbService _fileService;
        private readonly IUserService _userService;
        private readonly IFileServerService _fileServerService;
        public FileUploadController(IFileDbService fileService, IUserService userService, IFileServerService fileServerService)
        {
            _fileService = fileService;
            _userService = userService;
            _fileServerService = fileServerService;
        }
        public FileUploadController() : this(new FileDbService(), new UserService(), new FileServerService())
        {
        }
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UploadFileAsync(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid && upload != null)
            {
                var currentUser = await _userService.GetByUsernameAsync(this.User.Identity.Name);
                string privacy = Request.Form["Privacy"] == "false" ? "No" : "Yes";

               

                FileModel newFile = new FileModel()
                {
                    Name = upload.FileName,
                    NameSetByUser = Request.Form["Name"] == String.Empty ? upload.FileName : Request.Form["Name"],
                    Description = Request.Form["Description"],
                    DateOfUploading = DateTime.Now,
                    UserId = currentUser.Id,
                    UserName = currentUser.Username,
                    IsPrivate = privacy
                };

                int theSameFilesCount = 1;
                int i = newFile.Name.LastIndexOf('.');
                Regex thesameFileRegex = new Regex($"^{newFile.Name.Insert(i, "(\\s\\(\\d+\\))?")}$");
                foreach (var item in currentUser.Files)
                    if (thesameFileRegex.IsMatch(item.Name)) theSameFilesCount++;

                if (theSameFilesCount != 1)
                {
                    int index = newFile.Name.LastIndexOf('.');
                    string counter = $" ({theSameFilesCount})";
                    newFile.Name = newFile.Name.Insert(index, counter);
                }
                string root = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath("~")));
                string pathToFile = $"{root}\\DAL\\Files\\{currentUser.Username}\\{newFile.Name}";
                newFile.Path = pathToFile;

                await _fileService.AddAsync(newFile);
                _fileServerService.UploadFile(upload, currentUser.Username, newFile.Name);
                return RedirectToAction("ViewUserFilesAsync", "User");
            }
            return View("Index");
        }
    }
}

FileStorage/Controllers/ReviewController.cs
using BLL.DTO;
using BLL.Services;
using BLL.Services.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FileStorage.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewService _reviewService;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        public ReviewController(IReviewService reviewService, IUserService userService, IRoleService roleService)
        {
            _reviewService = reviewService;
            _userService = userService;
            _roleService = roleService;
        }
        public ReviewController() : this(new ReviewService(), new UserService(), new RoleService())
        {
        }
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            UserModel currentUser;
            try
            {
                currentUser = await _userService.GetByUsernameAsync(this.User.Identity.Name);
            }
            catch(ArgumentException)
            {
                currentUser = null;
            }

            if(currentUser != null)
            {
                ViewBag.CurrentUserId = currentUser.Id;
                var adminRoleId = (await _roleService.GetAllAsync()).FirstOrDefault(r => r.Name == "admin").Id;
                ViewBag.IsAdmin = currentUser.RoleId == adminRoleId;
            }

            return View((await _reviewService.GetAllAsync()).OrderByDescending(r => r.DateTime).ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddReviewAsync(ReviewModel review)
        {
            if (ModelState.IsValid)
            {
                UserModel currentUser;
                try
                {
                    currentUser = await _userService.GetByUsernameAsync(this.User.Identity.Name);
                }
                catch (ArgumentException)
                {
                    currentUser = null;
                }

                string roleName = "";
                if (currentUser != null) 
                {
                    var role = (await _roleService.GetByIdAsync(currentUser.RoleId)).Name;
                    if (role == "admin") roleName = "admin";
                }

                ReviewModel newReview = new ReviewModel()
                {
                    Username = Request.Form["name"] ?? User.Identity.GetUserName(),
                    Text = review.Text,
                    DateTime = DateTime.Now,
                    Role = roleName,
                };

                if (currentUser == null)
                {
                    newReview.UserId = null;
                    newReview.Username = "Guest " + newReview.Username;
                }
                else newReview.UserId = currentUser.Id;

                await _reviewService.AddAsync(newReview);
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> DeleteReviewAsync(Guid reviewId)
        {
            await _reviewService.DeleteAsync(reviewId);
            return RedirectToAction("Index");
        }
    }
}

FileStorage/Views/Shared/AdminPartial.cshtml
<li>@Html.ActionLink("User`s info", "ViewAllUsersDataAsync", "Admin")</li>
<li>@Html.ActionLink("All files", "ViewAllFilesAsync", "Admin")</li>

FileStorage/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "ShowDataAsync", "Account", routeValues: null, htmlAttributes: new { title = "Show data" })
            </li>
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Registration", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}

FileStorage/Views/Shared/UserPartial.cshtml
<li>@Html.ActionLink("Upload file", "Index", "FileUpload")</li>
<li>@Html.ActionLink("My files", "ViewUserFilesAsync", "User")</li>

FileStorage/Views/Shared/_Layout.cshtml
@using System.Web.Mvc;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="@Scripts.Url("~/Scripts/jquery-3.4.1.js")"></script>
    <link href="@Styles.Url("~/Content/MyStyle.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("File Storage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Reviews", "Index", "Review")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Change personal information", "ChangeData", "Account")</li>
                    }
                    @if (this.User.IsInRole("admin"))
                    {
                        @Html.Partial("AdminPartial")
                    }
                    else if (this.User.IsInRole("user"))
                    {
                        @Html.Partial("UserPartial")
                    }
                </ul>
                @Html.Partial("LoginPartial")
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <footer class="page-footer font-small special-color-dark pt-4">
        <div class="container">
            <ul class="list-unstyled list-inline text-center">
                <li class="list-inline-item">
                    <a class="btn-floating mx-1 social-networks" href="https://www.facebook.com/FileStorage" target="_blank">
                        <img src="~/Content/Images/SocialMediaIcons/facebook.png" alt="Facebook" />
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating mx-1 social-networks" href="https://www.instagram.com/file_storage/" target="_blank">
                        <img src="~/Content/Images/SocialMediaIcons/instagram.png" alt="Instagram" />
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating mx-1 social-networks" href="https://www.linkedin.com/company/filestorage/" target="_blank">
                        <img src="~/Content/Images/SocialMediaIcons/linkedin.png" alt="LinkedIn" />
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating mx-1 social-networks" href="https://twitter.com/Opacity_Storage" target="_blank">
                        <img src="~/Content/Images/SocialMediaIcons/twitter.png" alt="Twitter" />
                    </a>
                </li>
            </ul>
        </div>
        <div class="footer-copyright text-center py-3">
            <p>&copy; @DateTime.Now.Year - All rights reserved. Alexander Myroshnychenko</p>

        </div>
    </footer>

    @if (Request.Url.PathAndQuery == "/FileUpload/Index")
    {
        <script src="@Scripts.Url("~/Scripts/MyScript.js")"></script>
    }


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>